### ISSUE TITLE
Not required enum throws validation error on "" and undefined.

### ISSUE THREAD

**Issue by keeema** [ritchieanesco/json-schema-yup-transform#46]
# Steps to reproduce:

```javascript
const testSchema = {
      type: "object",
      $schema: "http://json-schema.org/draft-07/schema#",
      $id: "test",
      title: "Test",
      properties: {
        things: {
          type: "string",
          enum: ["a", "b"],
        },
      },
    };
    const yupschema = convertToYup(testSchema);

    console.log(
      yupschema!.isValidSync({
        things: "",
      })
    );

    console.log(
      yupschema!.isValidSync({
        things: null,
      })
    );

    console.log(
      yupschema!.isValidSync({
        things: undefined,
      })
    );
```

# Current behavior:
Validation error.

# Expected behavior:
No error because ```things``` is not required.

**Comment by ritchieanesco** [comment]
Thanks for using this library. This is the expected behavior when using enumerated values. See more information about it in the spec: http://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values.
You can add in "", null, and undefined types to the"things" property to prevent validation errors.
